"""
thumbnailer.py — populate thumbnail_path for all DB records

Three sources, in priority order:
  1. Photos library derivative JPEG (already generated by Photos, fastest)
  2. Flickr static URL (reconstructed from server/id/secret, no download)
  3. iCloud export via osxphotos (opt-in: requires --icloud flag)
     Exports are sequential and capped per run (--icloud-limit, default 50)
     to avoid overwhelming Photos.app via AppleScript.

Usage:
    python poller/thumbnailer.py --config config/config.yml
    python poller/thumbnailer.py --config config/config.yml --flickr-download
    python poller/thumbnailer.py --config config/config.yml --icloud --icloud-limit 100
    python poller/thumbnailer.py --config config/config.yml --limit 1000

The default mode sets thumbnail_path to either a local file path or a
Flickr URL — no downloads unless --flickr-download or --icloud is passed.
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

try:
    import osxphotos
except ImportError:
    osxphotos = None  # type: ignore[assignment]

sys.path.insert(0, str(Path(__file__).parent.parent))
from db.db import Database
from flickr.flickr_client import FlickrClient

log = logging.getLogger("blue-pearmain.thumbnailer")


def setup_logging(verbose: bool) -> None:
    from poller.bp_logging import configure

    configure("thumbs", verbose)


def derivative_path(uuid: str, library_path: str) -> str | None:
    """
    Return the path to Photos' pre-generated JPEG derivative for this UUID,
    or None if not present.
    """
    if not uuid:
        return None
    shard = uuid[0].lower()
    p = (
        Path(library_path)
        / "resources"
        / "derivatives"
        / "masters"
        / shard
        / f"{uuid}_4_5005_c.jpeg"
    )
    return str(p) if p.exists() else None


def flickr_url(flickr_id: str, secret: str, server: str) -> str | None:
    """Reconstruct the Flickr Large (1024px) static URL."""
    if not (flickr_id and secret and server):
        return None
    return f"https://live.staticflickr.com/{server}/{flickr_id}_{secret}_b.jpg"


def run(
    db: Database,
    library_path: str,
    thumb_root: Path | None,
    flickr_download: bool,
    client: FlickrClient | None,
    limit: int | None,
    dry_run: bool,
    icloud: bool = False,
    icloud_limit: int = 50,
):
    # Fetch all records without a thumbnail_path
    query = "SELECT id, uuid, flickr_id, flickr_secret, flickr_server FROM photos WHERE thumbnail_path IS NULL OR thumbnail_path = ''"
    if limit:
        query += f" LIMIT {limit}"

    rows = db.conn.execute(query).fetchall()
    log.info(f"Found {len(rows)} records needing thumbnails")

    local_count = flickr_url_count = download_count = icloud_resolved = icloud_queued = skipped = 0

    # Phase 0 — build iCloud lookup map (only when --icloud is set)
    # AppleScript-based exports must be sequential; no thread pool.
    uuid_to_photo: dict[str, Any] = {}
    tmpdir: str | None = None
    icloud_exported = 0

    if icloud and osxphotos is not None:
        photos_only_uuids = [r["uuid"] for r in rows if r["uuid"] and not r["flickr_id"]]
        if photos_only_uuids:
            photosdb = osxphotos.PhotosDB(dbfile=library_path)
            uuid_to_photo = {p.uuid: p for p in photosdb.photos(uuid=photos_only_uuids)}
            tmpdir = tempfile.mkdtemp()
            log.debug(
                "iCloud lookup ready: %d Photos-only records, %d found in library",
                len(photos_only_uuids),
                len(uuid_to_photo),
            )

    for row in rows:
        row_id = row["id"]
        uuid = row["uuid"] or ""
        flickr_id = row["flickr_id"] or ""
        secret = row["flickr_secret"] or ""
        server = row["flickr_server"] or ""

        thumb = None

        # 1. Local Photos derivative
        if uuid:
            thumb = derivative_path(uuid, library_path)
            if thumb:
                local_count += 1

        # 2. Flickr URL (no download — just store the URL as the path)
        if not thumb and flickr_id:
            url = flickr_url(flickr_id, secret, server)
            if url:
                if flickr_download and thumb_root and client:
                    # Actually download it
                    shard = flickr_id[:2]
                    dest = thumb_root / shard / f"{flickr_id}.jpg"
                    if dest.exists():
                        thumb = str(dest)
                    else:
                        ok = client.download_thumbnail(url, str(dest))
                        if ok:
                            thumb = str(dest)
                            download_count += 1
                else:
                    # Store the URL itself — Flask will redirect to it
                    thumb = url
                    flickr_url_count += 1

        # 3. iCloud export (sequential, capped by icloud_limit per run)
        if not thumb and icloud and uuid and icloud_exported < icloud_limit:
            photo = uuid_to_photo.get(uuid)
            if photo and photo.iscloudasset and photo.ismissing:
                try:
                    photo.export(tmpdir, use_photos_export=True)
                    icloud_exported += 1
                except Exception as exc:
                    log.warning("iCloud export failed for %s: %s", uuid, exc)
                thumb = derivative_path(uuid, library_path)
                if thumb:
                    icloud_resolved += 1
                else:
                    icloud_queued += 1
                    continue  # queued for next run, not truly skipped

        if not thumb:
            skipped += 1
            continue

        if not dry_run:
            db.conn.execute(
                "UPDATE photos SET thumbnail_path = ?, display_rotation = 0 WHERE id = ?",
                (thumb, row_id),
            )

    if tmpdir is not None:
        shutil.rmtree(tmpdir, ignore_errors=True)

    if not dry_run:
        db.conn.commit()

    icloud_msg = ""
    if icloud_resolved or icloud_queued:
        icloud_msg = (
            f", {icloud_resolved} iCloud resolved, {icloud_queued} iCloud queued (run again)"
        )
    log.info(
        f"Done: {local_count} local derivatives, {flickr_url_count} Flickr URLs, "
        f"{download_count} downloaded{icloud_msg}, {skipped} skipped"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Blue Pearmain thumbnailer")
    parser.add_argument("--config", default="config/config.yml")
    parser.add_argument(
        "--flickr-download",
        action="store_true",
        help="Download Flickr thumbnails instead of storing URLs",
    )
    parser.add_argument(
        "--icloud",
        action="store_true",
        help="Trigger sequential AppleScript export for iCloud-only photos (requires Photos.app)",
    )
    parser.add_argument(
        "--icloud-limit",
        type=int,
        default=50,
        help="Max iCloud exports per run when --icloud is set (default: 50)",
    )
    parser.add_argument("--limit", type=int, default=None, help="Process at most N records")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    setup_logging(args.verbose)
    log.info("Blue Pearmain thumbnailer starting")

    config_path = Path(args.config)
    with open(config_path) as f:
        config = yaml.safe_load(f)

    db_path = Path(config["database"]["path"]).expanduser()
    db = Database(db_path)

    library_path = str(Path(config.get("photos_library", {}).get("path", "")).expanduser())

    thumb_root: Path | None = None
    client: FlickrClient | None = None
    if args.flickr_download:
        thumb_root = Path(config["thumbnails"]["path"]).expanduser()
        thumb_root.mkdir(parents=True, exist_ok=True)
        client = FlickrClient.from_config(config)

    run(
        db=db,
        library_path=library_path,
        thumb_root=thumb_root,
        flickr_download=args.flickr_download,
        client=client,
        limit=args.limit,
        dry_run=args.dry_run,
        icloud=args.icloud,
        icloud_limit=args.icloud_limit,
    )

    db.close()


if __name__ == "__main__":
    main()
